project:
  type: website
  output-dir: docs

website:
  title: "Pratik Mahajan"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - research.qmd
      - fieldwork.qmd
      - teaching.qmd
      - outside_academy.qmd
     

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual





