project:
  type: website
  output-dir: docs
  
html-head:
  - meta:
      name: google-site-verification
      content: "7NwzhO4mpO6aQd9qc-4BPOMgPx3mSGD3fwlAp63evUQ"
      
website:
  title: "Pratik Mahajan"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - research.qmd
      - fieldwork.qmd
      - teaching.qmd
      - outside_academy.qmd
     

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual





