---
title: "Public Writing"
format:
  html:
    page-layout: full
    toc: false
---

-   **Review or Retention.** *The Times of India, Dec 2024* <button onclick="window.open('https://www.dropbox.com/scl/fi/w8pky5xiwz1irg7n26gyc/review-or-retention.jpg?rlkey=iuqxjbpq5uiro325t1vhtlveo&st=m8kaavak&dl=0', '_blank')">Read More</button>

-   **Ladki, bahin…but ethnic groups, caste too.** *The Times of India, Oct 2024* <button onclick="window.open('https://www.dropbox.com/scl/fi/24w79289gwvd244k1dtth/ladki-bahin.jpg?rlkey=no0zuwgt5oboyvk6p2ruu9ppt&st=c9jvb0ic&dl=0', '_blank')">Read More</button>

-   **Democracy's Slow March.** *With [Alyssa Heinze](https://alyssaheinze.github.io/).* *The Times of India, Oct 2024* <button onclick="window.open('https://www.dropbox.com/scl/fi/zbnhoumkpf03e9d9us870/democracy-on-a-slow-march.jpg?rlkey=bn9dqywsv6hsl9929ea86iuye&st=aos9cup6&dl=0', '_blank')">Read More</button>

-   **Maha Questions From Opposition's Small Allies.** *The Times of India, Sept 2024* <button onclick="window.open('https://www.dropbox.com/scl/fi/6gsbweho679ti79hxqq4i/maha-questions-from-small-allies.jpg?rlkey=5tycz1rzhz3uub3qc8h3hnd33&st=zq7jdtea&dl=0', '_blank')">Read More</button>

-   **Maharashtra LS polls have never been muddier.** *With [Vikramaditya Thakur](https://www.udel.edu/academics/colleges/cas/units/departments/anthropology/our-people/vikramaditya-thakur/).* *The Times of India, May 2024* <button onclick="window.open('https://www.dropbox.com/scl/fi/14kpsk52qgt1r71grpg24/maha-gondhal.jpg?rlkey=ku4raynl1p0njzze8o6c9wd0h&st=irf9eprv&dl=0', '_blank')">Read More</button>

-   **Why India’s Plan for A New Parliament May Spell A Challenging Future For Its Democracy?** *The McGill International Review, May 2021* <button onclick="window.open('https://www.mironline.ca/why-indias-plan-for-a-new-parliament-may-spell-a-challenging-future-for-its-democracy/', '_blank')">Read More</button>

-   **Education in India: A Duty Forsaken During COVID-19.** *The McGill International Review, July 2021* <button onclick="window.open('https://www.mironline.ca/education-in-india-a-right-forsaken-during-covid-19/', '_blank')">Read More</button>

-   **Guardians, citizens and the prohibition of private possessions in Plato's Republic.** *Liberalis Magazine, 2021* <button onclick="window.open('files/plato republic.jpg', '_blank')">Read More</button>

-   **Action as Addition: A Move Beyond Consequentializing.** *Fragments: McGill Philosophy Journal, 2021* <button onclick="window.open('https://00ff1226-c9ea-453e-baa6-e67819b43f30.filesusr.com/ugd/bc8784_cc48e86634aa4c4ca45aac27c1a3ee11.pdf', '_blank')">Read More</button>
